// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6UGAHqi_rQYYzIv5XNmAqrvRtRdPM9RY',
    appId: '1:665771093390:web:1958c08ca2af724c3948df',
    messagingSenderId: '665771093390',
    projectId: 'megz-app-95d60',
    authDomain: 'megz-app-95d60.firebaseapp.com',
    storageBucket: 'megz-app-95d60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_bpVvPzSKxxp1KjDd1BkaGNcU747k20Q',
    appId: '1:665771093390:android:12fa026d9a9b914c3948df',
    messagingSenderId: '665771093390',
    projectId: 'megz-app-95d60',
    storageBucket: 'megz-app-95d60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWOpYo6v5RW1QYN50A_SiBpcVABR9qkh0',
    appId: '1:665771093390:ios:8dbd5676a44b39723948df',
    messagingSenderId: '665771093390',
    projectId: 'megz-app-95d60',
    storageBucket: 'megz-app-95d60.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWOpYo6v5RW1QYN50A_SiBpcVABR9qkh0',
    appId: '1:665771093390:ios:8dbd5676a44b39723948df',
    messagingSenderId: '665771093390',
    projectId: 'megz-app-95d60',
    storageBucket: 'megz-app-95d60.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6UGAHqi_rQYYzIv5XNmAqrvRtRdPM9RY',
    appId: '1:665771093390:web:968f19e7eb4fe8d23948df',
    messagingSenderId: '665771093390',
    projectId: 'megz-app-95d60',
    authDomain: 'megz-app-95d60.firebaseapp.com',
    storageBucket: 'megz-app-95d60.appspot.com',
  );
}
